//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scritps/StateMachine/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PC"",
            ""id"": ""2beb90df-cb8e-4ba0-83e7-df217f6ebbfc"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""0bab4414-9d7a-4f32-a46f-4284f543392a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveGrounded"",
                    ""type"": ""Value"",
                    ""id"": ""68ca7cca-1dac-40ac-bbec-bcc95b6ba67d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveAerial"",
                    ""type"": ""Value"",
                    ""id"": ""9f12cd8d-08f7-4dd9-aa9d-32eb743bae65"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fly"",
                    ""type"": ""Value"",
                    ""id"": ""4535ba12-d9e8-4ea8-a29b-1ac5f374f01d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""23d0b5c7-d762-4d9a-9533-bd936b525f29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8843a459-d4a6-4192-a3dd-408a97b255f2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""536ae8a6-020c-4dc5-9bb4-d11180f6b374"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGrounded"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4874ab1d-950d-4789-9ccc-2feb8fce3bcc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGrounded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2fb4cc5b-0c61-4b53-b45e-2c77da0586f3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGrounded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""693b0ddc-d88f-40a2-9c08-b9042706e19f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAerial"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b93b6d9e-da83-46cc-a9f7-a1e2adfbc43e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAerial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dc8c7a13-4e99-489d-a048-f2ea8d217f15"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAerial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d9dc8bf7-b586-40da-a378-0baf40c00528"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAerial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2a97a8f1-c3b2-471c-a9ab-50a6060a1d0d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAerial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""348fa82c-0675-4f47-82a8-0247adef060c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b4efc66-49db-4015-b022-c7d63834c3b5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PC
        m_PC = asset.FindActionMap("PC", throwIfNotFound: true);
        m_PC_Jump = m_PC.FindAction("Jump", throwIfNotFound: true);
        m_PC_MoveGrounded = m_PC.FindAction("MoveGrounded", throwIfNotFound: true);
        m_PC_MoveAerial = m_PC.FindAction("MoveAerial", throwIfNotFound: true);
        m_PC_Fly = m_PC.FindAction("Fly", throwIfNotFound: true);
        m_PC_Dash = m_PC.FindAction("Dash", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PC
    private readonly InputActionMap m_PC;
    private IPCActions m_PCActionsCallbackInterface;
    private readonly InputAction m_PC_Jump;
    private readonly InputAction m_PC_MoveGrounded;
    private readonly InputAction m_PC_MoveAerial;
    private readonly InputAction m_PC_Fly;
    private readonly InputAction m_PC_Dash;
    public struct PCActions
    {
        private @Controls m_Wrapper;
        public PCActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_PC_Jump;
        public InputAction @MoveGrounded => m_Wrapper.m_PC_MoveGrounded;
        public InputAction @MoveAerial => m_Wrapper.m_PC_MoveAerial;
        public InputAction @Fly => m_Wrapper.m_PC_Fly;
        public InputAction @Dash => m_Wrapper.m_PC_Dash;
        public InputActionMap Get() { return m_Wrapper.m_PC; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PCActions set) { return set.Get(); }
        public void SetCallbacks(IPCActions instance)
        {
            if (m_Wrapper.m_PCActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_PCActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PCActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PCActionsCallbackInterface.OnJump;
                @MoveGrounded.started -= m_Wrapper.m_PCActionsCallbackInterface.OnMoveGrounded;
                @MoveGrounded.performed -= m_Wrapper.m_PCActionsCallbackInterface.OnMoveGrounded;
                @MoveGrounded.canceled -= m_Wrapper.m_PCActionsCallbackInterface.OnMoveGrounded;
                @MoveAerial.started -= m_Wrapper.m_PCActionsCallbackInterface.OnMoveAerial;
                @MoveAerial.performed -= m_Wrapper.m_PCActionsCallbackInterface.OnMoveAerial;
                @MoveAerial.canceled -= m_Wrapper.m_PCActionsCallbackInterface.OnMoveAerial;
                @Fly.started -= m_Wrapper.m_PCActionsCallbackInterface.OnFly;
                @Fly.performed -= m_Wrapper.m_PCActionsCallbackInterface.OnFly;
                @Fly.canceled -= m_Wrapper.m_PCActionsCallbackInterface.OnFly;
                @Dash.started -= m_Wrapper.m_PCActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PCActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PCActionsCallbackInterface.OnDash;
            }
            m_Wrapper.m_PCActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @MoveGrounded.started += instance.OnMoveGrounded;
                @MoveGrounded.performed += instance.OnMoveGrounded;
                @MoveGrounded.canceled += instance.OnMoveGrounded;
                @MoveAerial.started += instance.OnMoveAerial;
                @MoveAerial.performed += instance.OnMoveAerial;
                @MoveAerial.canceled += instance.OnMoveAerial;
                @Fly.started += instance.OnFly;
                @Fly.performed += instance.OnFly;
                @Fly.canceled += instance.OnFly;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
            }
        }
    }
    public PCActions @PC => new PCActions(this);
    public interface IPCActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMoveGrounded(InputAction.CallbackContext context);
        void OnMoveAerial(InputAction.CallbackContext context);
        void OnFly(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
    }
}
